Repository joseph704/FIFAONLINE4_INFO_APP, pull requests merged in 2023-02, with the labels that each got.

#16 [Feature] 시즌아이디(seasonId) 메타데이터 API 통신 후 Realm에 저장
  FIFAGG/FIFAGG.xcodeproj/project.pbxproj
  FIFAGG/FIFAGG/Data/Network/APIEndpoints.swift
  FIFAGG/FIFAGG/Data/Network/DataMapping/SeasonIdDTO.swift
  FIFAGG/FIFAGG/Data/PersistentStorages/Realm/DataMapping/RMSeasonId.swift
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
  FIFAGG/FIFAGG/Data/Repositories/Protocol/MetaInfoRepository.swift
  FIFAGG/FIFAGG/Domain/Usecase/DefaultFetchMetaInfoUseCase.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/Coordinator/DefaultIntroCoordinator.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/ViewModel/IntroViewModel.swift
  FIFAGG/FIFAGG/Utility/Constant/UserDefaultsKey.swift
Labels: Feature

#18 [Refactor] DefaultMetaInfoRepository 속 중복된 로직 처리
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
Labels: Refactor

#23 [Fix] 메타데이터들 fetch하는 Usecase의 execute메소드 반환값 Observable의 onCompleted 부분 한번만 호출되도록 수정
  FIFAGG/FIFAGG/Data/PersistentStorages/Realm/DefaultRealmStorage.swift
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
  FIFAGG/FIFAGG/Utility/Extension/Realm+Extension.swift
Labels: Bug

#24 [Feature] 선수 포지션(SPPosition) 메타데이터 API 통신 후 Realm에 저장
  FIFAGG/FIFAGG.xcodeproj/project.pbxproj
  FIFAGG/FIFAGG/Data/Network/APIEndpoints.swift
  FIFAGG/FIFAGG/Data/Network/DataMapping/SPPostionDTO.swift
  FIFAGG/FIFAGG/Data/PersistentStorages/Realm/DataMapping/RMSPPostion.swift
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
  FIFAGG/FIFAGG/Data/Repositories/Protocol/MetaInfoRepository.swift
  FIFAGG/FIFAGG/Domain/Usecase/DefaultFetchMetaInfoUseCase.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/Coordinator/DefaultIntroCoordinator.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/ViewModel/IntroViewModel.swift
  FIFAGG/FIFAGG/Utility/Constant/UserDefaultsKey.swift
Labels: Feature

#30 [Style] 오버로딩한 동일한 이름의 함수들에 마크다운 표시
  FIFAGG/FIFAGG/Data/Network/DataMapping/SpidDTO.swift
  FIFAGG/FIFAGG/Utility/Extension/Realm+Extension.swift
Labels: Style

#32 [Feature] 등급 식별자(division) 메타데이터 API 통신 후 Realm에 저장
  FIFAGG/FIFAGG.xcodeproj/project.pbxproj
  FIFAGG/FIFAGG/Data/Network/APIEndpoints.swift
  FIFAGG/FIFAGG/Data/Network/DataMapping/DivisionDTO.swift
  FIFAGG/FIFAGG/Data/PersistentStorages/Realm/DataMapping/RMDivision.swift
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
  FIFAGG/FIFAGG/Data/Repositories/Protocol/MetaInfoRepository.swift
  FIFAGG/FIFAGG/Domain/Usecase/DefaultFetchMetaInfoUseCase.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/Coordinator/DefaultIntroCoordinator.swift
  FIFAGG/FIFAGG/Presentation/IntroScene/ViewModel/IntroViewModel.swift
  FIFAGG/FIFAGG/Utility/Constant/UserDefaultsKey.swift
Labels: Feature

#34 [Chore] 공용 계정으로 Debug용 Signging 세팅
  FIFAGG/FIFAGG.xcodeproj/project.pbxproj
Labels: Chore

#36 [Fix] 매번 메타데이터 API response값 불러와 Realm에 저장하는 오류 해결
  FIFAGG/FIFAGG/Data/Repositories/DefaultMetaInfoRepository.swift
  FIFAGG/FIFAGG/Infrastructure/Network/DefaultDataTransferService.swift
  FIFAGG/FIFAGG/Infrastructure/Network/EndPoint.swift
Labels: Bug
